server:
  port: 9998
spring:
  application:
    name: emps
  cloud:                  #配置consul依赖
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///emp?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mybatis:
    mapper-locations: classpath:com/zihao/mapper/*.xml
    type-aliases-package: com.zihao.bean
