server:
  port: 8993

spring:
  application:
    name: gateway
  cloud:                  #配置consul依赖
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: user_routes   #指定路由唯一标识
          uri: lb://users   #使用负载均衡策略 //后面加服务注册中心上的名称
          predicates:
            - Path=/user/**

        - id: emp_routes
          uri: lb://emps
          predicates:
            - Path=/emp/**
